version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - my_network

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - my_network

networks:
  my_network:
