# Generated by Django 5.0.4 on 2024-05-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Inventory_Task',
        ),
        migrations.RenameModel(
            old_name='Employee_assigned',
            new_name='Employee_assigned_Task',
        ),
        migrations.CreateModel(
            name='Equipments_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipement_id', models.IntegerField()),
                ('Equipment_name', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField(default=1)),
                ('Condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Damaged', 'Damaged'), ('Broken', 'Broken')], max_length=20)),
                ('Assigned_to', models.ManyToManyField(blank=True, to='Task.employee_assigned_task')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='Equipments',
            field=models.ManyToManyField(to='Task.equipments_task'),
        ),
        migrations.DeleteModel(
            name='Equipments',
        ),
    ]
