# Generated by Django 4.2.13 on 2024-05-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0001_initial'),
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Equipments',
            field=models.ManyToManyField(to='Resource.equipments'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Inventory',
            field=models.ManyToManyField(to='Resource.inventory'),
        ),
    ]
