# Generated by Django 4.2.13 on 2024-05-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0002_budget'),
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipments_task',
            name='Assigned_to',
        ),
        migrations.DeleteModel(
            name='Inventory_Task',
        ),
        migrations.AlterField(
            model_name='task',
            name='Assigned_members',
            field=models.ManyToManyField(to='Resource.employee_assigned'),
        ),
        migrations.DeleteModel(
            name='Employee_assigned_Task',
        ),
        migrations.DeleteModel(
            name='Equipments_Task',
        ),
    ]
