# Generated by Django 5.0.4 on 2024-05-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_rename_inventory_inventory_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Description',
            field=models.CharField(max_length=300),
        ),
    ]
