# Generated by Django 4.2.13 on 2024-06-01 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_projectfile_remove_project_files_delete_file'),
        ('Resource', '0004_equipments_total_price_equipments_unit_price'),
        ('Task', '0002_remove_equipments_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=300)),
                ('Start_date', models.DateField(auto_now_add=True)),
                ('End_date', models.DateField()),
                ('Priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], max_length=20)),
                ('Status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled'), ('Overdue', 'Overdue')], max_length=20)),
                ('Last_updated', models.DateField(auto_now_add=True, null=True)),
                ('Assigned_members', models.ManyToManyField(to='Resource.employee_assigned')),
                ('Equipments', models.ManyToManyField(to='Resource.equipments')),
                ('Inventory', models.ManyToManyField(to='Resource.inventory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
            ],
        ),
    ]
