# Generated by Django 4.2.13 on 2024-06-01 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_subtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='project',
        ),
        migrations.AddField(
            model_name='subtask',
            name='Task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.task'),
        ),
    ]
