# Generated by Django 4.2.13 on 2024-06-05 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_rename_project_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='Task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='Task.task'),
        ),
    ]
