# Generated by Django 4.2.13 on 2024-05-15 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Task', '0001_initial'),
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencies',
            name='task_dependencies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.task'),
        ),
    ]
