# Generated by Django 4.2.13 on 2024-05-13 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0001_initial'),
        ('Task', '0003_alter_task_description'),
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_dependencies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resource.equipments')),
                ('hr_dependencies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resource.employee_assigned')),
                ('inventory_dependencies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resource.inventory')),
                ('task_dependencies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.task')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, upload_to='project_files/')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipments',
            name='Assigned_to',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.RenameField(
            model_name='projecttag',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='Milestones',
            field=models.ManyToManyField(blank=True, related_name='projects', to='Project.milestone'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Assigned_members',
            field=models.ManyToManyField(to='Resource.employee_assigned'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Equipments',
            field=models.ManyToManyField(to='Resource.equipments'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Inventory',
            field=models.ManyToManyField(to='Resource.inventory'),
        ),
        migrations.DeleteModel(
            name='Employee_assigned',
        ),
        migrations.DeleteModel(
            name='Equipments',
        ),
        migrations.AddField(
            model_name='project',
            name='Dependencies',
            field=models.ManyToManyField(related_name='dependencies', to='Project.dependencies'),
        ),
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='files', to='Project.file'),
        ),
    ]
