# Generated by Django 5.0.4 on 2024-05-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Last_updated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
