# Generated by Django 4.2.13 on 2024-05-13 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_dependencies_file_remove_equipments_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Project.project'),
        ),
    ]
