# Generated by Django 4.2.13 on 2024-05-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependencies',
            old_name='equipment_dependencies',
            new_name='Equipment_dependencies',
        ),
        migrations.RenameField(
            model_name='dependencies',
            old_name='hr_dependencies',
            new_name='HR_dependencies',
        ),
        migrations.RenameField(
            model_name='dependencies',
            old_name='inventory_dependencies',
            new_name='Inventory_dependencies',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='one_file',
            new_name='One_file',
        ),
        migrations.AlterField(
            model_name='project',
            name='Description',
            field=models.CharField(max_length=700),
        ),
    ]
