# Generated by Django 5.0.4 on 2024-05-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_remove_equipments_assigned_to_delete_inventory_and_more'),
        ('Resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Assigned_members',
            field=models.ManyToManyField(related_name='projects', to='Resource.employee_assigned'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Equipments',
            field=models.ManyToManyField(related_name='projects', to='Resource.equipments'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Inventory',
            field=models.ManyToManyField(related_name='projects', to='Resource.inventory'),
        ),
    ]
