# Generated by Django 4.2.13 on 2024-05-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Milestones',
            field=models.ManyToManyField(blank=True, related_name='milestone', to='Project.milestone'),
        ),
    ]
