# Generated by Django 5.0.4 on 2024-05-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_alter_project_assigned_members_and_more'),
        ('Resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Assigned_members',
            field=models.ManyToManyField(to='Resource.employee_assigned'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Equipments',
            field=models.ManyToManyField(to='Resource.equipments'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Inventory',
            field=models.ManyToManyField(to='Resource.inventory'),
        ),
    ]
