# Generated by Django 4.2.13 on 2024-05-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_alter_project_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.JSONField(default=list),
        ),
    ]
