# Generated by Django 4.2.13 on 2024-05-16 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0002_budget'),
        ('Project', '0003_rename_equipment_dependencies_dependencies_equipment_dependencies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencies',
            name='Buget_dependencies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Resource.budget'),
        ),
    ]
