# Generated by Django 5.0.4 on 2024-05-07 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_alter_project_assigned_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Assigned_members',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Equipments',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Inventory',
        ),
    ]
