# Generated by Django 4.2.13 on 2024-05-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_dependencies_buget_dependencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='file',
        ),
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.ManyToManyField(related_name='projects', to='Project.file'),
        ),
    ]
