# Generated by Django 4.2.13 on 2024-05-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_remove_project_file_project_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['Name']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['Name']},
        ),
        migrations.AlterField(
            model_name='project',
            name='Dependencies',
            field=models.ManyToManyField(to='Project.dependencies'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Milestones',
            field=models.ManyToManyField(blank=True, to='Project.milestone'),
        ),
    ]
