# Generated by Django 5.0.6 on 2024-05-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_project_assigned_members_project_equipments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttag',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='Milestones',
            field=models.ManyToManyField(blank=True, related_name='projects', to='Project.milestone'),
        ),
    ]
