# Generated by Django 4.2.13 on 2024-05-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_alter_milestone_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.IntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='files',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
