# Generated by Django 4.2.13 on 2024-05-13 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0001_initial'),
        ('Task', '0003_alter_task_description'),
        ('Project', '0007_rename_name_projecttag_name_project_milestones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_dependencies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resource.equipments')),
                ('hr_dependencies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resource.employee_assigned')),
                ('inventory_dependencies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resource.inventory')),
                ('task_dependencies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.task')),
            ],
        ),
    ]
