# Generated by Django 4.2.13 on 2024-06-01 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_workspace_rename_project_tag_project_project_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='WorkSpace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.workspace'),
        ),
    ]
