# Generated by Django 4.2.13 on 2024-05-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Dependencies',
            field=models.ManyToManyField(related_name='dependencies', to='Project.dependencies'),
        ),
    ]
