# Generated by Django 4.2.13 on 2024-06-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0009_project_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_archive',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_bookmarked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_archive',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_bookmarked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
