# Generated by Django 4.2.13 on 2024-05-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0009_project_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Files',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
