# Generated by Django 4.2.13 on 2024-05-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0010_project_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Files',
        ),
    ]
