# Generated by Django 4.2.13 on 2024-06-04 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_rename_project_task_project'),
        ('Project', '0010_project_is_archive_project_is_bookmarked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencies',
            name='task_dependencies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.task'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Milestones',
            field=models.ManyToManyField(blank=True, related_name='project_milestone', to='Project.milestone'),
        ),
    ]
