# Generated by Django 4.2.13 on 2024-06-04 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_rename_project_task_project'),
        ('Project', '0011_dependencies_task_dependencies_milestone_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencies',
            name='dependent_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='Task.task'),
        ),
    ]
