# Generated by Django 4.2.13 on 2024-06-05 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0006_alter_subtask_task'),
        ('Project', '0012_dependencies_dependent_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencies',
            name='task_dependencies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='Task.task'),
        ),
    ]
