# Generated by Django 4.2.13 on 2024-05-24 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0007_projectfile_remove_project_files_delete_file'),
        ('Task', '0002_remove_equipments_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EffortCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('remind', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.task')),
            ],
        ),
    ]
