# Generated by Django 4.2.13 on 2024-05-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Effort', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effortcalculation',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
