# Generated by Django 4.2.13 on 2024-06-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Effort', '0003_alter_effortcalculation_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effortcalculation',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='effortcalculation',
            name='start_time',
            field=models.DateField(),
        ),
    ]
