# Generated by Django 4.2.13 on 2024-06-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Effort', '0004_alter_effortcalculation_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effortcalculation',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='effortcalculation',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
