# Generated by Django 4.2.13 on 2024-06-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Effort', '0006_alter_effortcalculation_remind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effortcalculation',
            name='start_time',
            field=models.DateTimeField(default=None),
        ),
    ]
