# Generated by Django 4.2.13 on 2024-06-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Effort', '0007_alter_effortcalculation_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effortcalculation',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='effortcalculation',
            name='start_time',
            field=models.DateField(),
        ),
    ]
