# Generated by Django 4.2.13 on 2024-06-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Workspace_name', models.CharField(max_length=100)),
                ('Priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], max_length=20)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('is_archive', models.BooleanField(default=False, null=True)),
                ('is_bookmarked', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
