# Generated by Django 4.2.13 on 2024-05-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_assigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_id', models.IntegerField()),
                ('Employee_name', models.CharField(max_length=30)),
                ('Employee_email', models.EmailField(max_length=254)),
                ('Employee_phone', models.IntegerField()),
                ('Employee_address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Quantity', models.IntegerField()),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=30)),
                ('Client_name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=30)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipement_id', models.IntegerField()),
                ('Equipment_name', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField(default=1)),
                ('Condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Damaged', 'Damaged'), ('Broken', 'Broken')], max_length=20)),
                ('Assigned_to', models.ManyToManyField(to='Resource.employee_assigned')),
            ],
        ),
    ]
