# Generated by Django 4.2.13 on 2024-05-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100)),
                ('Amount_in_words', models.CharField(blank=True, max_length=400)),
                ('Payment_method', models.CharField(choices=[('Bank', 'Bank'), ('Check', 'Check'), ('Cash', 'Cash'), ('Credit Card', 'Credit Card')], max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
