# Generated by Django 4.2.13 on 2024-05-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0002_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='size',
            new_name='Size',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='Client_name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='Phone',
        ),
        migrations.AddField(
            model_name='inventory',
            name='Category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='Total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='Unit_Price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
