# Generated by Django 4.2.13 on 2024-05-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0003_rename_size_inventory_size_remove_inventory_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='Total_price',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='equipments',
            name='Unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True),
        ),
    ]
